name: Trigger auto deployment for cskinator

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cskinator-AutoDeployTrigger-98000a9b-1e9d-4206-953a-afab0ba071e0.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CSKINATOR_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}01-Docker/web-app
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: devmatchpredictor.azurecr.io
          registryUsername: ${{ secrets.CSKINATOR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CSKINATOR_REGISTRY_PASSWORD }}
          containerAppName: cskinator
          resourceGroup: hacks
          imageToBuild: devmatchpredictor.azurecr.io/rcbinator-web-app:${{ github.sha }}
          
            

     

