name: Trigger auto deployment for devops-rcbnator

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/devops-rcbnator-AutoDeployTrigger-4d974d67-3e8d-4325-a0e2-29d29e1670ba.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEVOPSRCBNATOR_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEVOPSRCBNATOR_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEVOPSRCBNATOR_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/01-docker/web-app
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: devopsworkshopyderabad.azurecr.io
          registryUsername: ${{ secrets.DEVOPSRCBNATOR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEVOPSRCBNATOR_REGISTRY_PASSWORD }}
          containerAppName: devops-rcbnator
          resourceGroup: just-for-hacks
          imageToBuild: devopsworkshopyderabad.azurecr.io/devops-rcbnator:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


